name: super_x_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.15.2
  firebase_storage: ^12.3.6
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotion/
    - assets/sunscreen/
    - assets/Serum/
    - assets/moisturiser/
    - assets/bodyWash/
    - assets/problems/
    - assets/darkCircles/
    - assets/Wrinkle/
    - assets/drynessF/
    - assets/drynessM/
    - assets/drynessF/
    - assets/pornima/
    - assets/bhandare/
    - assets/derma/
    - assets/dove/
    - assets/garnier/
    - assets/mamaearth/
    - assets/neiva/
    - assets/pilgrim/
    - assets/Vasaline/
    - assets/wow/
    - assets/final logosplash.avif
    - assets/
    
  
     